/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ug.frontend;

import java.util.ArrayList;
import javax.swing.JFrame;
import ug.backend.BazaDanych;
import ug.backend.Koncert;

/**
 *
 * @author Konrad
 */
public class KoncertFrame extends javax.swing.JFrame {
    private BazaDanych bazaDanych;
    private ArrayList koncerty;
    private Koncert koncert;
    private int indeks;
    
    /**
     * Creates new form KoncertFrame
     */
    public KoncertFrame() {
        initComponents();
        bazaDanych= new BazaDanych();
        koncerty=bazaDanych.wszystkieKoncerty();
        indeks=0;       
        pokazKoncert(indeks);
        bPoprzedni_k.setEnabled(false);
        
        tCzas_k.setEditable(false);
        tMiejsce_k.setEditable(false);
        tZespol_k.setEditable(false);
        tBiletyDostepne_k.setEditable(false);
        tId_k.setEditable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }    
    private void pokazKoncert(int indeks) {
        koncert=(Koncert)koncerty.get(indeks);
        tId_k.setText(String.valueOf(koncert.getId_k()));
        tZespol_k.setText(koncert.getZespol_k());
        tMiejsce_k.setText(koncert.getMiejsce_k());
        tCzas_k.setText(koncert.getCzas_k());
        tBiletyDostepne_k.setText(String.valueOf(koncert.getBilety_k()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenu1 = new javax.swing.JMenu();
        bSzukaj_k = new javax.swing.JButton();
        bNastepny_k = new javax.swing.JButton();
        bPoprzedni_k = new javax.swing.JButton();
        tZespol_k = new javax.swing.JTextField();
        tMiejsce_k = new javax.swing.JTextField();
        tBiletyDostepne_k = new javax.swing.JTextField();
        tZespol_szukaj = new javax.swing.JTextField();
        tMiejsce_szukaj = new javax.swing.JTextField();
        bZarezerwuj_k = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tEmail_k = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tCzas_k = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tBiletyRezerwowane_k = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tId_k = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bSzukaj_k.setText("Szukaj");
        bSzukaj_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSzukaj_kActionPerformed(evt);
            }
        });

        bNastepny_k.setText("Nastepny");
        bNastepny_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNastepny_kActionPerformed(evt);
            }
        });

        bPoprzedni_k.setText("Poprzedni");
        bPoprzedni_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPoprzedni_kActionPerformed(evt);
            }
        });

        tZespol_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tZespol_kActionPerformed(evt);
            }
        });

        tMiejsce_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMiejsce_kActionPerformed(evt);
            }
        });

        tBiletyDostepne_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBiletyDostepne_kActionPerformed(evt);
            }
        });

        tZespol_szukaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tZespol_szukajActionPerformed(evt);
            }
        });

        tMiejsce_szukaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMiejsce_szukajActionPerformed(evt);
            }
        });

        bZarezerwuj_k.setText("Zarezerwuj");
        bZarezerwuj_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZarezerwuj_kActionPerformed(evt);
            }
        });

        jLabel1.setText("Zespół");

        jLabel2.setText("Miejscowość");

        tEmail_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmail_kActionPerformed(evt);
            }
        });

        jLabel3.setText("Data");

        jLabel4.setText("Dostępne bilety");

        jLabel5.setText("Adres email");

        jLabel6.setText("Zespół");

        jLabel7.setText("Miejscowość");

        tCzas_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCzas_kActionPerformed(evt);
            }
        });

        jLabel8.setText("Liczba biletów");

        tBiletyRezerwowane_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBiletyRezerwowane_kActionPerformed(evt);
            }
        });

        jLabel9.setText("Id");

        tId_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tId_kActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bNastepny_k, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tMiejsce_k)
                            .addComponent(tCzas_k, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tBiletyDostepne_k)
                            .addComponent(tZespol_k)
                            .addComponent(jLabel2)
                            .addComponent(bPoprzedni_k, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tId_k, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tEmail_k)
                            .addComponent(tZespol_szukaj)
                            .addComponent(tMiejsce_szukaj)
                            .addComponent(bSzukaj_k)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bZarezerwuj_k)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tBiletyRezerwowane_k, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tBiletyRezerwowane_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(14, 14, 14)
                        .addComponent(tId_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tZespol_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tMiejsce_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tEmail_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bZarezerwuj_k)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tZespol_szukaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCzas_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMiejsce_szukaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tBiletyDostepne_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSzukaj_k))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNastepny_k)
                    .addComponent(bPoprzedni_k))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNastepny_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNastepny_kActionPerformed
        // TODO add your handling code here:
        if(indeks<koncerty.size()-1){
            indeks+=1;
            this.pokazKoncert(indeks);
        
            if(indeks==koncerty.size()-1) {
                bNastepny_k.setEnabled(false);
            }else{
                bPoprzedni_k.setEnabled(true);
            }
        }
    }//GEN-LAST:event_bNastepny_kActionPerformed

    private void tMiejsce_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMiejsce_kActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tMiejsce_kActionPerformed

    private void tZespol_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tZespol_kActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tZespol_kActionPerformed

    private void tMiejsce_szukajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMiejsce_szukajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMiejsce_szukajActionPerformed

    private void tBiletyDostepne_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBiletyDostepne_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBiletyDostepne_kActionPerformed

    private void bZarezerwuj_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZarezerwuj_kActionPerformed
        // TODO add your handling code here:
        int Dostepne = Integer.parseInt(tBiletyDostepne_k.getText());
        int Rezerwowane = Integer.parseInt(tBiletyRezerwowane_k.getText());
        int Zaktualizowane=Dostepne- Rezerwowane;
        String newId = tEmail_k.getText()+tId_k.getText();
        if(Rezerwowane>0 && Dostepne>= Rezerwowane){
            bazaDanych.zarezerwuj(newId,Integer.parseInt(tId_k.getText()), 
                    tEmail_k.getText(), Rezerwowane,Zaktualizowane, Integer.parseInt(tId_k.getText()));
                 
            koncerty = bazaDanych.wszystkieKoncerty ();//przeładowanie po rezerwacji
       
        }
    }//GEN-LAST:event_bZarezerwuj_kActionPerformed
        
    private void tZespol_szukajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tZespol_szukajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tZespol_szukajActionPerformed

    private void tCzas_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCzas_kActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tCzas_kActionPerformed

    private void bSzukaj_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSzukaj_kActionPerformed
        // TODO add your handling code here:
        for(int indeks=0; indeks<koncerty.size(); indeks++){ //dla kazdego elementu z listy:
            koncert=(Koncert)koncerty.get(indeks); //tworzymy zmienną koncert do której przypisujemy element o typie Koncert
            koncert.getZespol_k();//pobieramy nazweZespolu kazdego elementu
            koncert.getMiejsce_k(); //pobieramy nazweMiejsca kazdego elementu
                if(tZespol_szukaj.getText().equals(koncert.getZespol_k()) && 
                        tMiejsce_szukaj.getText().equals(koncert.getMiejsce_k())){    
                            pokazKoncert(indeks);
            }   
        }
    }//GEN-LAST:event_bSzukaj_kActionPerformed

    private void tEmail_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmail_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEmail_kActionPerformed

    private void bPoprzedni_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPoprzedni_kActionPerformed
        // TODO add your handling code here:
         if(indeks>0) {
            indeks-=1;
            this.pokazKoncert(indeks);
        
            if(indeks==0) {
                bPoprzedni_k.setEnabled(false);
            }else{
                bNastepny_k.setEnabled(true);
            }            
        }
    }//GEN-LAST:event_bPoprzedni_kActionPerformed

    private void tBiletyRezerwowane_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBiletyRezerwowane_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBiletyRezerwowane_kActionPerformed

    private void tId_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tId_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tId_kActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KoncertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KoncertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KoncertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KoncertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KoncertFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bNastepny_k;
    private javax.swing.JButton bPoprzedni_k;
    private javax.swing.JButton bSzukaj_k;
    private javax.swing.JButton bZarezerwuj_k;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField tBiletyDostepne_k;
    private javax.swing.JTextField tBiletyRezerwowane_k;
    private javax.swing.JTextField tCzas_k;
    private javax.swing.JTextField tEmail_k;
    private javax.swing.JTextField tId_k;
    private javax.swing.JTextField tMiejsce_k;
    private javax.swing.JTextField tMiejsce_szukaj;
    private javax.swing.JTextField tZespol_k;
    private javax.swing.JTextField tZespol_szukaj;
    // End of variables declaration//GEN-END:variables

    
}
