/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ug.frontend;

import javax.swing.JFrame;

/**
 *
 * @author Konrad
 */
public class StartFrame extends javax.swing.JFrame {

    private KoncertFrame koncertFrame;
    private RezerwacjaFrame rezerwacjaFrame;
    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
        koncertFrame= new KoncertFrame();
        koncertFrame.setTitle("Dostepne koncerty");
        koncertFrame.setSize(800,600);
        
        rezerwacjaFrame= new RezerwacjaFrame();
        rezerwacjaFrame.setTitle("Dostepne Rezerwacje");
        rezerwacjaFrame.setSize(800,600);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mPlik = new javax.swing.JMenu();
        mZakoncz = new javax.swing.JMenuItem();
        mEdycja = new javax.swing.JMenu();
        mKoncerty = new javax.swing.JMenuItem();
        mRezerwacja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mPlik.setText("Plik");

        mZakoncz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mZakoncz.setText("Zakończ");
        mZakoncz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mZakonczActionPerformed(evt);
            }
        });
        mPlik.add(mZakoncz);

        jMenuBar1.add(mPlik);

        mEdycja.setText("Edycja");

        mKoncerty.setText("Dostępne koncerty");
        mKoncerty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKoncertyActionPerformed(evt);
            }
        });
        mEdycja.add(mKoncerty);

        mRezerwacja.setText("Dokonane rezerwacje");
        mRezerwacja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRezerwacjaActionPerformed(evt);
            }
        });
        mEdycja.add(mRezerwacja);

        jMenuBar1.add(mEdycja);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mZakonczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mZakonczActionPerformed
        // TODO add your handling code here:
        System.exit(0);
       
       
        
    }//GEN-LAST:event_mZakonczActionPerformed

    private void mKoncertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKoncertyActionPerformed
        // TODO add your handling code here:
         koncertFrame.setVisible(true);
    }//GEN-LAST:event_mKoncertyActionPerformed

    private void mRezerwacjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRezerwacjaActionPerformed
        // TODO add your handling code here:
         rezerwacjaFrame.setVisible(true);
    }//GEN-LAST:event_mRezerwacjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mEdycja;
    private javax.swing.JMenuItem mKoncerty;
    private javax.swing.JMenu mPlik;
    private javax.swing.JMenuItem mRezerwacja;
    private javax.swing.JMenuItem mZakoncz;
    // End of variables declaration//GEN-END:variables
}
